### ISSUE TITLE
does not generate valid json for Windows paths

### ISSUE THREAD

**Issue by ltorok** [HanSolo/javafinder#3]
Backslashes not are escaped.

Example:
"search_path":"C:\Program Files\Java\" (wrong) -> "search_path":"C:\\Program Files\\Java\\" (good)

**Comment by HanSolo** [comment]
Right…the windows problem again 😜 Thx for the heads up 👍🏻😁

**Comment by HanSolo** [comment]
Should hopefully now be fixed in 17.0.21 :)

**Comment by ltorok** [comment]
Now is better, but is still not good. If is used default search path for Windows, then in json is this: "search_path":"C:\Program Files\Java" - above, my first comment. Maybe bug in eu.hansolo.javafinder.Main in method findJava(final String[]) -> for set search_path.

**Comment by HanSolo** [comment]
So what exactly is the problem with that? The missing backslash at the end or are there still single backslashes?

**Comment by ltorok** [comment]
IMHO are there still single backslashes. See lines below

https://github.com/HanSolo/javafinder/blob/db18a9435c078c90d7bfe93a4df43b24963157b4/src/main/java/eu/hansolo/javafinder/Main.java#L146

and

https://github.com/HanSolo/javafinder/blob/db18a9435c078c90d7bfe93a4df43b24963157b4/src/main/java/eu/hansolo/javafinder/Main.java#L159

**Comment by HanSolo** [comment]
Will take a look tomorrow…today is Java BBQ 😁 Thx for reporting, appreciated 👍🏻

**Comment by HanSolo** [comment]
Ok, found some time to fix it, should now work in version 17.0.23

**Comment by ltorok** [comment]
In version 17.0.23 is ok now. Thanks.
